import type { ThemeConfig } from "antd";
import type { ThemeId } from "@/context/ThemeContext";

const DESIGN_COLORS = {
  primary: "#cc785c",
  primaryActive: "#a9583e",
  primaryDisabled: "#e6dfd8",
  ink: "#141413",
  body: "#3d3d3a",
  bodyStrong: "#252523",
  muted: "#6c6a64",
  mutedSoft: "#8e8b82",
  hairline: "#e6dfd8",
  hairlineSoft: "#ebe6df",
  canvas: "#faf9f5",
  surfaceSoft: "#f5f0e8",
  surfaceCard: "#efe9de",
  surfaceCreamStrong: "#e8e0d2",
  surfaceDark: "#181715",
  surfaceDarkElevated: "#252320",
  surfaceDarkSoft: "#1f1e1b",
  onPrimary: "#ffffff",
  onDark: "#faf9f5",
  onDarkSoft: "#a09d96",
  accentTeal: "#5db8a6",
  accentAmber: "#e8a55a",
  success: "#5db872",
  successSoft: "#3d8a52",
  warning: "#d4a017",
  warningSoft: "#b88a0f",
  error: "#c64545",
  errorSoft: "#a53838",
  info: "#5c738b",
  infoSoft: "#4a6077",
};

const DESIGN_ROUNDED = {
  xs: 4,
  sm: 6,
  md: 8,
  lg: 12,
  xl: 16,
  pill: 9999,
};

const DESIGN_TYPOGRAPHY = {
  fontFamilyDisplay: '"Copernicus", "Tiempos Headline", "Noto Serif SC", "Cormorant Garamond", Georgia, serif',
  fontFamilyUi: '"Inter", "StyreneB", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  fontFamilyCode: '"JetBrains Mono", ui-monospace, "Cascadia Code", "Sarasa Mono SC", "Noto Sans Mono CJK SC", monospace',
};

export const inkMindLightTheme: ThemeConfig = {
  token: {
    colorPrimary: DESIGN_COLORS.primary,
    colorPrimaryHover: DESIGN_COLORS.primaryActive,
    colorPrimaryActive: DESIGN_COLORS.primaryActive,
    colorSuccess: DESIGN_COLORS.success,
    colorSuccessHover: DESIGN_COLORS.successSoft,
    colorWarning: DESIGN_COLORS.warning,
    colorWarningHover: DESIGN_COLORS.warningSoft,
    colorError: DESIGN_COLORS.error,
    colorErrorHover: DESIGN_COLORS.errorSoft,
    colorInfo: DESIGN_COLORS.info,
    colorInfoHover: DESIGN_COLORS.infoSoft,
    colorBgBase: DESIGN_COLORS.canvas,
    colorBgContainer: DESIGN_COLORS.canvas,
    colorBgElevated: DESIGN_COLORS.canvas,
    colorBgLayout: DESIGN_COLORS.surfaceSoft,
    colorBgSpotlight: DESIGN_COLORS.surfaceCard,
    colorText: DESIGN_COLORS.ink,
    colorTextSecondary: DESIGN_COLORS.body,
    colorTextTertiary: DESIGN_COLORS.muted,
    colorTextQuaternary: DESIGN_COLORS.mutedSoft,
    colorBorder: DESIGN_COLORS.hairline,
    colorBorderSecondary: DESIGN_COLORS.hairlineSoft,
    colorFill: DESIGN_COLORS.surfaceCard,
    colorFillSecondary: DESIGN_COLORS.surfaceSoft,
    colorFillTertiary: DESIGN_COLORS.hairline,
    colorFillQuaternary: DESIGN_COLORS.canvas,
    borderRadius: DESIGN_ROUNDED.md,
    borderRadiusLG: DESIGN_ROUNDED.lg,
    borderRadiusSM: DESIGN_ROUNDED.sm,
    borderRadiusXS: DESIGN_ROUNDED.xs,
    fontSize: 14,
    fontSizeLG: 16,
    fontSizeXL: 18,
    fontSizeHeading1: 64,
    fontSizeHeading2: 48,
    fontSizeHeading3: 36,
    fontSizeHeading4: 28,
    fontSizeHeading5: 22,
    lineHeight: 1.55,
    lineHeightHeading1: 1.05,
    lineHeightHeading2: 1.1,
    lineHeightHeading3: 1.15,
    lineHeightHeading4: 1.2,
    lineHeightHeading5: 1.3,
    fontWeightStrong: 500,
    fontFamily: DESIGN_TYPOGRAPHY.fontFamilyUi,
    fontFamilyCode: DESIGN_TYPOGRAPHY.fontFamilyCode,
    controlHeight: 40,
    controlHeightLG: 48,
    controlHeightSM: 32,
    marginXXS: 4,
    marginXS: 8,
    marginSM: 12,
    marginMD: 16,
    marginLG: 24,
    marginXL: 32,
    marginXXL: 48,
    paddingXXS: 4,
    paddingXS: 8,
    paddingSM: 12,
    paddingMD: 16,
    paddingLG: 24,
    paddingXL: 32,
  },
  components: {
    Button: {
      borderRadius: DESIGN_ROUNDED.md,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      primaryColor: DESIGN_COLORS.onPrimary,
      defaultBg: DESIGN_COLORS.canvas,
      defaultColor: DESIGN_COLORS.ink,
      defaultBorderColor: DESIGN_COLORS.hairline,
      defaultHoverBg: DESIGN_COLORS.surfaceCard,
      defaultHoverColor: DESIGN_COLORS.ink,
      defaultHoverBorderColor: DESIGN_COLORS.hairline,
      fontSize: 14,
      fontWeight: 500,
    },
    Input: {
      borderRadius: DESIGN_ROUNDED.md,
      controlHeight: 40,
      activeBorderColor: DESIGN_COLORS.primary,
      hoverBorderColor: DESIGN_COLORS.hairline,
      colorBgContainer: DESIGN_COLORS.canvas,
      colorText: DESIGN_COLORS.ink,
      colorTextPlaceholder: DESIGN_COLORS.mutedSoft,
    },
    Select: {
      borderRadius: DESIGN_ROUNDED.md,
      controlHeight: 40,
      colorBgContainer: DESIGN_COLORS.canvas,
      colorText: DESIGN_COLORS.ink,
    },
    Card: {
      borderRadiusLG: DESIGN_ROUNDED.lg,
      colorBgContainer: DESIGN_COLORS.canvas,
      colorBorderSecondary: DESIGN_COLORS.hairline,
    },
    Tabs: {
      borderRadius: DESIGN_ROUNDED.md,
      itemColor: DESIGN_COLORS.muted,
      itemActiveColor: DESIGN_COLORS.ink,
      itemHoverColor: DESIGN_COLORS.ink,
      inkBarColor: DESIGN_COLORS.primary,
    },
    Modal: {
      borderRadiusLG: DESIGN_ROUNDED.lg,
      colorBgElevated: DESIGN_COLORS.canvas,
    },
    Message: {
      contentBg: DESIGN_COLORS.canvas,
    },
    Alert: {
      borderRadiusLG: DESIGN_ROUNDED.md,
      colorInfoBg: "rgba(93, 184, 166, 0.12)",
      colorInfoText: "#7dc9ba",
      colorSuccessBg: "rgba(93, 184, 114, 0.12)",
      colorSuccessText: "#7cc98d",
      colorWarningBg: "rgba(232, 165, 90, 0.12)",
      colorWarningText: "#f0b87a",
      colorErrorBg: "rgba(198, 69, 69, 0.12)",
      colorErrorText: "#d65a5a",
    },
    Tag: {
      borderRadiusSM: DESIGN_ROUNDED.sm,
      defaultBg: DESIGN_COLORS.surfaceCard,
      defaultColor: DESIGN_COLORS.ink,
    },
    Table: {
      borderRadiusLG: DESIGN_ROUNDED.lg,
      headerBg: DESIGN_COLORS.surfaceSoft,
      rowHoverBg: DESIGN_COLORS.surfaceCard,
    },
    Dropdown: {
      borderRadiusLG: DESIGN_ROUNDED.lg,
      colorBgElevated: DESIGN_COLORS.canvas,
    },
    Menu: {
      borderRadiusLG: DESIGN_ROUNDED.lg,
      itemBg: "transparent",
      itemHoverBg: DESIGN_COLORS.surfaceCard,
      itemSelectedBg: DESIGN_COLORS.surfaceCard,
      itemColor: DESIGN_COLORS.ink,
      itemHoverColor: DESIGN_COLORS.ink,
      itemSelectedColor: DESIGN_COLORS.primary,
    },
    Avatar: {
      borderRadiusLG: DESIGN_ROUNDED.pill,
      colorBgBase: DESIGN_COLORS.primary,
    },
    Badge: {
      borderRadiusSM: DESIGN_ROUNDED.pill,
    },
    Tooltip: {
      borderRadiusLG: DESIGN_ROUNDED.sm,
      colorBgSpotlight: DESIGN_COLORS.ink,
      colorTextLightSolid: DESIGN_COLORS.onPrimary,
    },
    Popover: {
      borderRadiusLG: DESIGN_ROUNDED.lg,
      colorBgElevated: DESIGN_COLORS.canvas,
    },
    DatePicker: {
      borderRadius: DESIGN_ROUNDED.md,
      controlHeight: 40,
    },
    Checkbox: {
      borderRadius: DESIGN_ROUNDED.sm,
      colorPrimary: DESIGN_COLORS.primary,
    },
    Radio: {
      colorPrimary: DESIGN_COLORS.primary,
    },
    Switch: {
      borderRadiusLG: DESIGN_ROUNDED.pill,
      colorPrimary: DESIGN_COLORS.primary,
    },
    Slider: {
      borderRadiusLG: DESIGN_ROUNDED.pill,
      colorPrimary: DESIGN_COLORS.primary,
      railBg: DESIGN_COLORS.hairline,
      trackBg: DESIGN_COLORS.primary,
    },
    Progress: {
      borderRadius: DESIGN_ROUNDED.pill,
      colorPrimary: DESIGN_COLORS.primary,
      remainingColor: DESIGN_COLORS.surfaceCard,
    },
    Spin: {
      colorPrimary: DESIGN_COLORS.primary,
    },
    Empty: {
      colorTextDescription: DESIGN_COLORS.muted,
    },
    Collapse: {
      borderRadiusLG: DESIGN_ROUNDED.lg,
      colorBgContainer: DESIGN_COLORS.canvas,
      colorBorder: DESIGN_COLORS.hairline,
    },
    Timeline: {
      colorBorder: DESIGN_COLORS.hairline,
    },
    Divider: {
      colorSplit: DESIGN_COLORS.hairlineSoft,
    },
    Breadcrumb: {
      colorText: DESIGN_COLORS.muted,
      lastItemColor: DESIGN_COLORS.ink,
      linkColor: DESIGN_COLORS.muted,
      linkHoverColor: DESIGN_COLORS.primary,
    },
    Pagination: {
      borderRadius: DESIGN_ROUNDED.sm,
      colorPrimary: DESIGN_COLORS.primary,
      itemBg: DESIGN_COLORS.canvas,
      itemActiveBg: DESIGN_COLORS.primary,
      itemActiveColor: DESIGN_COLORS.onPrimary,
    },
    Steps: {
      colorPrimary: DESIGN_COLORS.primary,
    },
  },
};

export const inkMindSepiaTheme: ThemeConfig = {
  token: {
    colorPrimary: "#b89a78",
    colorPrimaryHover: "#c9a882",
    colorPrimaryActive: "#a68b6a",
    colorSuccess: "#7a9a6b",
    colorSuccessHover: "#8aab7b",
    colorWarning: "#b89a78",
    colorWarningHover: "#c9a882",
    colorError: "#a87a7a",
    colorErrorHover: "#b88a8a",
    colorInfo: "#7a8b9a",
    colorInfoHover: "#8a9cab",
    colorBgBase: "#faf6e9",
    colorBgContainer: "#faf6e9",
    colorBgElevated: "#faf6e9",
    colorBgLayout: "#f4ecd8",
    colorBgSpotlight: "#e8dcc0",
    colorText: "#5c4b37",
    colorTextSecondary: "#7a6855",
    colorTextTertiary: "#8b7355",
    colorTextQuaternary: "#a08060",
    colorBorder: "#d4c4a8",
    colorBorderSecondary: "#e0d0b0",
    colorFill: "#e8dcc0",
    colorFillSecondary: "#ebe4d8",
    colorFillTertiary: "#f0e9df",
    colorFillQuaternary: "#f5f0e8",
    borderRadius: DESIGN_ROUNDED.md,
    borderRadiusLG: DESIGN_ROUNDED.lg,
    borderRadiusSM: DESIGN_ROUNDED.sm,
    borderRadiusXS: DESIGN_ROUNDED.xs,
    fontSize: 14,
    fontFamily: DESIGN_TYPOGRAPHY.fontFamilyUi,
    fontFamilyCode: DESIGN_TYPOGRAPHY.fontFamilyCode,
    controlHeight: 40,
    controlHeightLG: 48,
    controlHeightSM: 32,
  },
  components: {
    Button: {
      borderRadius: DESIGN_ROUNDED.md,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
    },
    Input: {
      borderRadius: DESIGN_ROUNDED.md,
      controlHeight: 40,
    },
    Select: {
      borderRadius: DESIGN_ROUNDED.md,
      controlHeight: 40,
    },
    Card: {
      borderRadiusLG: DESIGN_ROUNDED.lg,
    },
    Tabs: {
      borderRadius: DESIGN_ROUNDED.md,
    },
    Modal: {
      borderRadiusLG: DESIGN_ROUNDED.lg,
    },
    Message: {
      contentBg: "#faf6e9",
    },
    Alert: {
      borderRadiusLG: DESIGN_ROUNDED.md,
      colorInfoBg: "rgba(93, 184, 166, 0.12)",
      colorInfoText: "#7dc9ba",
      colorSuccessBg: "rgba(93, 184, 114, 0.12)",
      colorSuccessText: "#7cc98d",
      colorWarningBg: "rgba(232, 165, 90, 0.12)",
      colorWarningText: "#f0b87a",
      colorErrorBg: "rgba(198, 69, 69, 0.15)",
      colorErrorText: "#d65a5a",
    },
    Tag: {
      borderRadiusSM: DESIGN_ROUNDED.sm,
    },
    Table: {
      borderRadiusLG: DESIGN_ROUNDED.lg,
    },
  },
};

export const inkMindDarkTheme: ThemeConfig = {
  token: {
    colorPrimary: "#cc785c",
    colorPrimaryHover: "#d88a6d",
    colorPrimaryActive: "#a9583e",
    colorSuccess: "#5db872",
    colorSuccessHover: "#7cc98d",
    colorWarning: "#e8a55a",
    colorWarningHover: "#f0b87a",
    colorError: "#c64545",
    colorErrorHover: "#d65a5a",
    colorInfo: "#5db8a6",
    colorInfoHover: "#7dc9ba",
    colorBgBase: "#181715",
    colorBgContainer: "#181715",
    colorBgElevated: "#252320",
    colorBgLayout: "#1f1e1b",
    colorBgSpotlight: "#252320",
    colorText: "#faf9f5",
    colorTextSecondary: "#a09d96",
    colorTextTertiary: "#8e8b82",
    colorTextQuaternary: "#6c6a64",
    colorBorder: "#373530",
    colorBorderSecondary: "#2a2825",
    colorFill: "#252320",
    colorFillSecondary: "#1f1e1b",
    colorFillTertiary: "#373530",
    colorFillQuaternary: "#181715",
    borderRadius: DESIGN_ROUNDED.md,
    borderRadiusLG: DESIGN_ROUNDED.lg,
    borderRadiusSM: DESIGN_ROUNDED.sm,
    borderRadiusXS: DESIGN_ROUNDED.xs,
    fontSize: 14,
    fontFamily: DESIGN_TYPOGRAPHY.fontFamilyUi,
    fontFamilyCode: DESIGN_TYPOGRAPHY.fontFamilyCode,
    controlHeight: 40,
    controlHeightLG: 48,
    controlHeightSM: 32,
    marginXXS: 4,
    marginXS: 8,
    marginSM: 12,
    marginMD: 16,
    marginLG: 24,
    marginXL: 32,
    marginXXL: 48,
  },
  components: {
    Button: {
      borderRadius: DESIGN_ROUNDED.md,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      primaryColor: "#ffffff",
      defaultBg: "#252320",
      defaultColor: "#faf9f5",
      defaultBorderColor: "#373530",
      defaultHoverBg: "#373530",
      defaultHoverColor: "#faf9f5",
      defaultHoverBorderColor: "#373530",
      fontSize: 14,
      fontWeight: 500,
    },
    Input: {
      borderRadius: DESIGN_ROUNDED.md,
      controlHeight: 40,
      colorBgContainer: "#252320",
      colorText: "#faf9f5",
      colorTextPlaceholder: "#8e8b82",
      activeBorderColor: "#cc785c",
      hoverBorderColor: "#373530",
    },
    Select: {
      borderRadius: DESIGN_ROUNDED.md,
      controlHeight: 40,
      colorBgContainer: "#252320",
      colorText: "#faf9f5",
    },
    Card: {
      borderRadiusLG: DESIGN_ROUNDED.lg,
      colorBgContainer: "#181715",
      colorBorderSecondary: "#373530",
    },
    Tabs: {
      borderRadius: DESIGN_ROUNDED.md,
      itemColor: "#a09d96",
      itemActiveColor: "#faf9f5",
      itemHoverColor: "#faf9f5",
      inkBarColor: "#cc785c",
    },
    Modal: {
      borderRadiusLG: DESIGN_ROUNDED.lg,
      colorBgElevated: "#252320",
    },
    Message: {
      contentBg: "#252320",
    },
    Alert: {
      borderRadiusLG: DESIGN_ROUNDED.md,
    },
    Tag: {
      borderRadiusSM: DESIGN_ROUNDED.sm,
      defaultBg: "#252320",
      defaultColor: "#faf9f5",
    },
    Table: {
      borderRadiusLG: DESIGN_ROUNDED.lg,
      headerBg: "#1f1e1b",
      rowHoverBg: "#252320",
    },
    Dropdown: {
      borderRadiusLG: DESIGN_ROUNDED.lg,
      colorBgElevated: "#252320",
    },
    Menu: {
      borderRadiusLG: DESIGN_ROUNDED.lg,
      itemBg: "transparent",
      itemHoverBg: "#252320",
      itemSelectedBg: "#252320",
      itemColor: "#faf9f5",
      itemHoverColor: "#faf9f5",
      itemSelectedColor: "#cc785c",
    },
    Avatar: {
      borderRadiusLG: DESIGN_ROUNDED.pill,
      colorBgBase: "#cc785c",
    },
    Tooltip: {
      borderRadiusLG: DESIGN_ROUNDED.sm,
      colorBgSpotlight: "#373530",
      colorTextLightSolid: "#faf9f5",
    },
    Popover: {
      borderRadiusLG: DESIGN_ROUNDED.lg,
      colorBgElevated: "#252320",
    },
  },
};

export function getThemeConfig(theme: ThemeId): ThemeConfig {
  switch (theme) {
    case "dark":
      return inkMindDarkTheme;
    case "sepia":
      return inkMindSepiaTheme;
    case "light":
    default:
      return inkMindLightTheme;
  }
}

export const inkMindTheme = inkMindLightTheme;

export { DESIGN_COLORS, DESIGN_ROUNDED, DESIGN_TYPOGRAPHY };
