async (page) => {
  if (!page.url().startsWith('http://127.0.0.1:5198/')) throw new Error('Use the isolated UI fixture only');
  const check = (value, message) => { if (!value) throw new Error(message); };
  const control = async (data) => page.request.post('http://127.0.0.1:18991/__test/control', { data });
  await page.goto('http://127.0.0.1:5198/');
  await page.getByRole('searchbox', { name: '搜索作品名称或类型' }).fill('山海');
  await page.locator('.library-item').first().waitFor();
  check(await page.locator('.library-item').count() === 1, 'Library search must filter works');
  await page.getByRole('searchbox', { name: '搜索作品名称或类型' }).fill('');
  await page.getByRole('button', { name: 'plus 创建新作品', exact: true }).click();
  const editor = page.getByRole('textbox', { name: '章节正文', exact: true });
  await editor.waitFor();
  const novelPath = page.url().replace('/write', '');
  const novelId = Number(novelPath.split('/').at(-1));
  const chapters = async () => (await page.request.get(`http://127.0.0.1:18991/novels/${novelId}/chapters`)).json();
  check((await chapters()).length === 1 && await editor.inputValue() === '', 'New work must open exactly one blank chapter');
  await page.getByRole('textbox', { name: '请输入章节标题', exact: true }).fill('第一盏灯');
  await control({ delay: 1500, failSaves: false });
  const firstSave = page.waitForRequest(r => r.method() === 'PATCH' && r.url().includes(`/novels/${novelId}/chapters/`));
  await editor.fill('雨落在窗台上。');
  await firstSave;
  const final = '雨落在窗台上。\n\n　　她点亮了第一盏灯。';
  await editor.fill(final);
  await page.getByRole('button', { name: '作品列表', exact: true }).click();
  await page.getByRole('heading', { name: '我的作品', exact: true }).waitFor();
  await control({ delay: 0 });
  check((await chapters())[0].content === final, 'Navigation during a delayed save must persist the latest edit');
  await page.getByRole('button', { name: '紧凑列表', exact: true }).click();
  const item = page.locator('.library-item').filter({ has: page.locator(`a[href^="/novels/${novelId}/write"]`) });
  await item.waitFor();
  check((await item.innerText()).includes(`${Array.from(final.replace(/\s/g, '')).length} 字`), 'Library count must match the manuscript');
  check((await item.innerText()).includes('1 章'), 'Library should count the initial chapter');
  await page.screenshot({ path: '/tmp/inkmind-library-list.png', animations: 'disabled' });
  await item.locator('.library-continue').click();
  await editor.waitFor();
  check(await editor.inputValue() === final, 'Continue writing must restore saved content');
  await control({ failSaves: true });
  const retryText = final + '\n\n　　灯光没有熄灭。';
  await editor.fill(retryText);
  await page.getByRole('button', { name: '作品列表', exact: true }).click();
  await page.getByRole('alert').filter({ hasText: '测试网络错误' }).waitFor();
  check(page.url().includes('/write'), 'Failed save must block navigation');
  check(await editor.inputValue() === retryText, 'Failed save must retain the author input');
  await control({ failSaves: false });
  await page.getByRole('button', { name: '重试保存', exact: true }).click();
  await page.getByRole('status').filter({ hasText: '已保存' }).waitFor();
  check((await chapters())[0].content === retryText, 'Retry must save the latest text');
  await page.getByRole('button', { name: '作品列表', exact: true }).click();
  await item.waitFor();
  await item.getByRole('button').click();
  await page.getByRole('menuitem').filter({ hasText: '导出' }).click();
  await page.getByRole('dialog').waitFor();
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click();
  await item.getByRole('button').click();
  await page.getByRole('menuitem').filter({ hasText: '删除' }).click();
  await page.getByRole('dialog').getByRole('button', { name: /^取\s*消$/ }).click();
  check((await chapters()).length === 1, 'Cancelling deletion must preserve the work');
  return 'PASS: search, first chapter creation, delayed save navigation, progress counts, continue writing, failed save retry, export and delete cancel';
}
