async (page) => {
  if (!page.url().startsWith('http://127.0.0.1:5198/')) throw new Error('Use the isolated UI fixture only');
  const check = (value, message) => { if (!value) throw new Error(message); };
  const state = async () => (await page.request.get('http://127.0.0.1:18991/__test/state')).json();
  const control = async (data) => { await page.request.post('http://127.0.0.1:18991/__test/control', { data }); };
  if (await page.getByRole('button', { name: '放弃预览', exact: true }).isVisible()) await page.getByRole('button', { name: '放弃预览', exact: true }).click();
  await page.getByRole('button', { name: '生成预览', exact: true }).click();
  await page.getByRole('checkbox', { name: '选择修改 2', exact: true }).waitFor();
  const initial = await state();
  const original = initial.chapters.find(c => c.id === 901);
  await page.getByRole('checkbox', { name: '选择修改 2', exact: true }).uncheck();
  await page.getByText('概要修改', { exact: true }).click();
  await page.getByRole('checkbox', { name: '采用新概要', exact: true }).uncheck();
  await page.getByRole('button', { name: '定位修改 2', exact: true }).click();
  check(await page.getByRole('button', { name: '对比', exact: true }).getAttribute('aria-pressed') === 'true', 'Locate must show central comparison');
  await page.getByRole('button', { name: '确认稿', exact: true }).click();
  const candidate = await page.getByRole('textbox', { name: '编辑 AI 草稿，采用后保存', exact: true }).inputValue();
  check(candidate.trimStart().startsWith('风停的时候'), 'First change should be accepted');
  check(candidate.includes('　　是盐。') && !candidate.includes('是海盐'), 'Second change should preserve original');
  check(await page.getByRole('textbox', { name: '请输入章节标题' }).inputValue() === original.title, 'Title selection must be respected');
  await page.waitForTimeout(1200);
  check((await state()).writes.length === initial.writes.length && (await state()).confirmations.length === 0, 'Preview must never autosave');
  await page.screenshot({ path: '/tmp/inkmind-review-new.png' });
  await control({ failSaves: true });
  await page.getByRole('button', { name: '采纳并保存', exact: true }).click();
  await page.getByRole('alert').filter({ hasText: '测试网络错误' }).waitFor();
  check(await page.getByRole('textbox', { name: '编辑 AI 草稿，采用后保存' }).inputValue() === candidate, 'Failed confirmation must retain reviewed text');
  check((await state()).confirmations.length === 0, 'Failed confirmation must not mutate server');
  await control({ failSaves: false });
  await page.getByRole('button', { name: '采纳并保存', exact: true }).click();
  await page.getByRole('button', { name: '生成预览', exact: true }).waitFor();
  await page.waitForTimeout(1200);
  const saved = await state();
  check(saved.confirmations.length === 1, 'Exactly one successful confirmation');
  check(saved.confirmations[0].content === candidate && saved.confirmations[0].title === 'AI 预览标题' && saved.confirmations[0].summary === original.summary, 'Confirmed payload must equal the reviewed draft');
  check(saved.chapters.find(c => c.id === 901).content === candidate, 'Server must retain accepted text');
  await page.getByRole('button', { name: '生成预览', exact: true }).click();
  await page.getByRole('button', { name: '放弃预览', exact: true }).waitFor();
  await page.getByRole('button', { name: '放弃预览', exact: true }).click();
  check(await page.getByRole('textbox', { name: '章节正文' }).inputValue() === candidate, 'Cancel must restore the pre-generation content');
  check((await state()).confirmations.length === 1, 'Cancel must not confirm');
  return 'PASS: partial acceptance, metadata choice, no preview autosave, failed confirmation retry, and cancel restoration';
}
